//! Packet crafting support.
//!
//! Crafting is intentionally separate from packet viewing/parsing. Protocol
//! modules own their builders, while this module owns stack composition and
//! cross-layer context.
//!
//! A stack is built in two passes:
//!
//! 1. Each layer is measured from outermost to innermost, producing a
//!    [`CraftPlan`](crate::packet::craft::CraftPlan) that contains its layer length and
//!    total length.
//! 2. The stack allocates one final `Vec<u8>` and asks each layer to write into
//!    its final byte slice. Child layers are written before parents, so parent
//!    checksums can inspect already-written child bytes.

use std::{net::Ipv4Addr, ops::Div};

use crate::packet::{
    Packet,
    layer::{Layer, Protocol},
};

/// Owned crafted packet bytes plus crafted layer metadata.
///
/// This is an alias for [`Packet<Vec<u8>>`], so crafted packets can be viewed
/// with the same `Packet::layer(...)`, `Packet::layer_viewer(...)`,
/// `Packet::as_bytes()`, and `Packet::into_bytes()` APIs as parsed packets.
pub type CraftedPacket = Packet<Vec<u8>>;

/// Error returned while crafting packet bytes.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum CraftError {
    /// A length did not fit in the protocol field that carries it.
    #[error("{protocol}: {field} length {len} exceeds maximum {max}")]
    LengthOverflow {
        /// Protocol being built.
        protocol: &'static str,
        /// Length field being filled.
        field: &'static str,
        /// Requested length.
        len: usize,
        /// Maximum representable length.
        max: usize,
    },

    /// A user-provided length field is too small for the generated bytes.
    #[error("{protocol}: {field} length {len} is smaller than required minimum {min}")]
    InvalidLength {
        /// Protocol being built.
        protocol: &'static str,
        /// Length field being filled.
        field: &'static str,
        /// User-provided length.
        len: usize,
        /// Minimum valid length.
        min: usize,
    },

    /// A user-provided field value is structurally invalid.
    #[error("{protocol}: invalid {field} value {value}: {reason}")]
    InvalidField {
        /// Protocol being built.
        protocol: &'static str,
        /// Field name.
        field: &'static str,
        /// User-provided value.
        value: usize,
        /// Reason the value is invalid.
        reason: &'static str,
    },

    /// A raw payload was followed by another protocol layer.
    #[error("raw payload must be the terminal layer")]
    RawMustBeTerminal,

    /// The stack contained no layers.
    #[error("packet stack is empty")]
    EmptyStack,
}

/// Cross-layer context available while measuring and writing inner layers.
///
/// Parent layers use this to pass pseudo-header information to children. For
/// example, IPv4 sets [`Ipv4CraftContext`] before measuring/writing TCP or UDP
/// so those builders can calculate transport checksums without reparsing the
/// outer header.
#[derive(Debug, Clone, Copy, Default)]
pub struct CraftContext {
    /// IPv4 pseudo-header fields available to transport-layer builders.
    pub ipv4: Option<Ipv4CraftContext>,
}

impl CraftContext {
    /// Return a copy of this context with IPv4 pseudo-header fields set.
    ///
    /// IPv4 builders call this from [`child_context`](CraftLayer::child_context) before the
    /// child layer is measured or written.
    #[inline]
    pub fn with_ipv4(mut self, src: Ipv4Addr, dst: Ipv4Addr) -> Self {
        self.ipv4 = Some(Ipv4CraftContext { src, dst });
        self
    }
}

/// IPv4 pseudo-header fields used by TCP and UDP checksums.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Ipv4CraftContext {
    /// Source IPv4 address.
    pub src: Ipv4Addr,
    /// Destination IPv4 address.
    pub dst: Ipv4Addr,
}

/// Description of a measured child layer.
///
/// This is passed to [`measure`](CraftLayer::measure). It gives the parent just enough
/// information to size itself and infer discriminator fields such as
/// EtherType or IP protocol without exposing mutable packet bytes.
#[derive(Debug, Clone, Copy)]
pub struct CraftChildPlan {
    protocol: &'static dyn Protocol,
    len: usize,
}

impl CraftChildPlan {
    /// Return the child protocol identity.
    ///
    /// Parent builders can compare this with known layer marker types using
    /// [`is`](CraftChildPlan::is).
    #[inline]
    pub fn protocol(&self) -> &'static dyn Protocol {
        self.protocol
    }

    /// Return the child total length in octets.
    #[inline]
    pub fn len(&self) -> usize {
        self.len
    }

    /// Return whether the child is empty.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Return whether this child uses the given protocol marker.
    ///
    /// This is the preferred way for built-in and custom parents to infer
    /// discriminator fields without matching on a closed enum.
    #[inline]
    pub fn is<P: Protocol>(&self, protocol: P) -> bool {
        self.protocol.id() == protocol.id()
    }
}

/// Description of a child layer already written into a parent buffer.
///
/// This is passed to [`write`](CraftLayer::write). The child bytes already live in the
/// final packet buffer, so parent layers can calculate checksums or infer
/// fields without allocating or concatenating.
#[derive(Debug, Clone, Copy)]
pub struct CraftChild {
    protocol: &'static dyn Protocol,
    offset: usize,
    len: usize,
}

impl CraftChild {
    /// Return the child protocol identity.
    #[inline]
    pub fn protocol(&self) -> &'static dyn Protocol {
        self.protocol
    }

    /// Return the child offset relative to the current layer buffer.
    ///
    /// If an Ethernet frame contains an IPv4 packet, this is normally `14`.
    /// Child layers always start immediately after the parent layer bytes.
    #[inline]
    pub fn offset(&self) -> usize {
        self.offset
    }

    /// Return the child total length in octets.
    #[inline]
    pub fn len(&self) -> usize {
        self.len
    }

    /// Return whether the child is empty.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Return the child bytes from a current-layer buffer.
    ///
    /// The `layer_bytes` argument must be the same slice passed to the
    /// parent's [`write`](CraftLayer::write) implementation.
    #[inline]
    pub fn bytes<'a>(&self, layer_bytes: &'a [u8]) -> &'a [u8] {
        &layer_bytes[self.offset..self.offset + self.len]
    }

    /// Return the child mutable bytes from a current-layer buffer.
    ///
    /// Use this only when a parent intentionally needs to patch child bytes
    /// after the child has written itself.
    #[inline]
    pub fn bytes_mut<'a>(&self, layer_bytes: &'a mut [u8]) -> &'a mut [u8] {
        &mut layer_bytes[self.offset..self.offset + self.len]
    }

    /// Return whether this child uses the given protocol.
    #[inline]
    pub fn is<P: Protocol>(&self, protocol: P) -> bool {
        self.protocol.id() == protocol.id()
    }
}

/// Measured layout for one crafted layer.
///
/// `layer_len` is the protocol layer length recorded in `Packet::layers()`;
/// `total_len` is the full byte span occupied by this layer plus child bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CraftPlan {
    layer_len: usize,
    total_len: usize,
}

impl CraftPlan {
    /// Create a measured layout for one crafted layer.
    ///
    /// `layer_len` is the number of bytes that should be recorded as this
    /// protocol layer. `total_len` is the byte span reserved for this layer and
    /// any child bytes. When a child exists, the stack writes it at
    /// `layer_len`.
    pub fn new(layer_len: usize, total_len: usize) -> Self {
        Self {
            layer_len,
            total_len,
        }
    }

    /// Return this layer's length in the final packet layer table.
    #[inline]
    pub fn layer_len(&self) -> usize {
        self.layer_len
    }

    /// Return this layer plus child total length.
    #[inline]
    pub fn total_len(&self) -> usize {
        self.total_len
    }
}

/// Trait implemented by types that can craft one protocol layer.
///
/// Custom protocol builders implement this trait to participate in `/`
/// composition. Implementations should be deterministic: `measure()` decides
/// the final lengths and offsets, and `write()` must fill exactly the bytes
/// described by that plan.
pub trait CraftLayer: std::fmt::Debug + 'static {
    /// Return this layer's type name for diagnostics.
    ///
    /// Override this when a custom builder wants shorter error messages than
    /// Rust's full type path.
    fn name(&self) -> &'static str {
        std::any::type_name::<Self>()
    }

    /// Return this layer's protocol identity.
    ///
    /// The returned marker is used for layer-table entries and by parent
    /// builders that infer discriminator fields from child protocol type.
    fn protocol(&self) -> &'static dyn Protocol;

    /// Return the context that should be used while measuring and writing the
    /// child layer.
    ///
    /// Most layers can keep the default. Parent protocols that affect child
    /// checksums, such as IPv4, should return an updated context.
    fn child_context(&self, context: CraftContext) -> CraftContext {
        context
    }

    /// Measure this layer around an optional child.
    ///
    /// This function must not write packet bytes. It should validate explicit
    /// length fields, infer default header lengths, and return the layout that
    /// `write()` will later use.
    fn measure(
        &self,
        context: CraftContext,
        child: Option<CraftChildPlan>,
    ) -> Result<CraftPlan, CraftError>;

    /// Write this layer into its final byte slice.
    ///
    /// The stack writes the child first, so `bytes` already contains child
    /// bytes at `child.offset()` when this method is called. Implementations
    /// should write their own header in place, usually through the protocol's
    /// mutable viewer.
    fn write(
        &self,
        context: CraftContext,
        plan: CraftPlan,
        child: Option<CraftChild>,
        bytes: &mut [u8],
    ) -> Result<(), CraftError>;
}

/// A stack of craftable protocol layers.
///
/// Stacks are usually created with the `/` operator:
///
/// ```
/// # use maja::prelude::*;
/// # use std::net::Ipv4Addr;
/// let packet = (eth!()
///     / ipv4!(src: Ipv4Addr::new(192, 0, 2, 1), dst: Ipv4Addr::new(192, 0, 2, 2))
///     / udp!(src: 12345, dst: 53)
///     / raw!(b"hello"))
///     .build()
///     .expect("packet can be crafted");
///
/// assert_eq!(packet.as_bytes().len(), 14 + 20 + 8 + 5);
/// ```
#[derive(Debug, Default)]
pub struct PacketStack {
    layers: Vec<Box<dyn CraftLayer>>,
}

impl PacketStack {
    /// Create an empty packet stack.
    ///
    /// This is useful for code that wants to push layers conditionally. Most
    /// callers can use `/` composition or [`from_layer`](PacketStack::from_layer) instead.
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a packet stack from one layer.
    ///
    /// The layer can be any built-in or custom type implementing
    /// [`CraftLayer`].
    pub fn from_layer(layer: impl CraftLayer) -> Self {
        let mut stack = Self::default();
        stack.push_layer(layer);
        stack
    }

    /// Append one layer to the end of the stack.
    ///
    /// The first layer is the outermost layer. Pushing `Eth`, then `Ipv4`,
    /// then `Udp` creates an Ethernet frame containing IPv4 containing UDP.
    pub fn push_layer(&mut self, layer: impl CraftLayer) {
        self.layers.push(Box::new(layer));
    }

    /// Build the stack into a [`Packet<Vec<u8>>`].
    ///
    /// This performs one measurement pass, allocates the final packet buffer
    /// once, writes each layer into its final slice, and returns a packet whose
    /// layer table can be queried immediately.
    pub fn build(&self) -> Result<CraftedPacket, CraftError> {
        if self.layers.is_empty() {
            return Err(CraftError::EmptyStack);
        }

        let measured = self.measure()?;
        let mut bytes = vec![0; measured[0].plan.total_len()];
        self.write_measured(&measured, bytes.as_mut_slice())?;

        let mut layers = Vec::new();
        collect_layers(&measured, &mut layers);

        Ok(Packet { bytes, layers })
    }

    /// Build the stack and return only the owned byte buffer.
    ///
    /// Use this when the caller only needs bytes for a socket or capture
    /// writer and does not need `Packet::layer(...)` accessors. Unlike
    /// [`build`](PacketStack::build), this skips packet layer-table construction.
    pub fn to_bytes(&self) -> Result<Vec<u8>, CraftError> {
        if self.layers.is_empty() {
            return Err(CraftError::EmptyStack);
        }

        let measured = self.measure()?;
        let mut bytes = vec![0; measured[0].plan.total_len()];
        self.write_measured(&measured, bytes.as_mut_slice())?;
        Ok(bytes)
    }

    /// Measure all layers from innermost to outermost.
    ///
    /// Contexts are calculated from outermost to innermost, then each layer is
    /// measured from innermost to outermost so parents can see child length and
    /// protocol identity without child bytes existing yet.
    fn measure(&self) -> Result<Vec<MeasuredLayer>, CraftError> {
        let mut contexts = Vec::with_capacity(self.layers.len());
        let mut context = CraftContext::default();
        for layer in &self.layers {
            contexts.push(context);
            context = layer.child_context(context);
        }

        let mut child_plan = None;
        let mut measured = Vec::with_capacity(self.layers.len());

        for (index, layer) in self.layers.iter().enumerate().rev() {
            let context = contexts[index];
            let plan = layer.measure(context, child_plan)?;
            validate_plan(layer.as_ref(), plan, child_plan)?;

            measured.push(MeasuredLayer {
                protocol: layer.protocol(),
                plan,
                context,
                offset: 0,
            });
            child_plan = Some(CraftChildPlan {
                protocol: layer.protocol(),
                len: plan.total_len(),
            });
        }

        measured.reverse();
        set_layer_offsets(&mut measured)?;
        Ok(measured)
    }

    /// Write measured layers into the final packet buffer.
    ///
    /// Layers are written from innermost to outermost so parent checksum logic
    /// can read finalized child bytes from the same allocation.
    fn write_measured(
        &self,
        measured: &[MeasuredLayer],
        bytes: &mut [u8],
    ) -> Result<(), CraftError> {
        for index in (0..measured.len()).rev() {
            let layer = &self.layers[index];
            let measured_layer = measured[index];
            let offset = measured_layer.offset;
            let end = checked_add_len(
                layer.name(),
                "total_len",
                offset,
                measured_layer.plan.total_len(),
            )?;
            let child = if index + 1 < measured.len() {
                Some(CraftChild {
                    protocol: measured[index + 1].protocol,
                    offset: measured_layer.plan.layer_len(),
                    len: measured[index + 1].plan.total_len(),
                })
            } else {
                None
            };

            layer.write(
                measured_layer.context,
                measured_layer.plan,
                child,
                &mut bytes[offset..end],
            )?;
        }

        Ok(())
    }
}

/// Validate that a layer's measured layout can contain its child.
fn validate_plan(
    layer: &dyn CraftLayer,
    plan: CraftPlan,
    child: Option<CraftChildPlan>,
) -> Result<(), CraftError> {
    if plan.total_len() < plan.layer_len() {
        return Err(CraftError::InvalidLength {
            protocol: layer.name(),
            field: "total_len",
            len: plan.total_len(),
            min: plan.layer_len(),
        });
    }
    if let Some(child) = child {
        let child_end = checked_add_len(layer.name(), "child_end", plan.layer_len(), child.len())?;
        if child_end > plan.total_len() {
            return Err(CraftError::InvalidLength {
                protocol: layer.name(),
                field: "total_len",
                len: plan.total_len(),
                min: child_end,
            });
        }
    }

    Ok(())
}

/// Set absolute offsets for measured layers in outer-to-inner order.
fn set_layer_offsets(measured: &mut [MeasuredLayer]) -> Result<(), CraftError> {
    let mut offset = 0;
    for layer in measured {
        layer.offset = offset;
        offset = checked_add_len("packet", "offset", offset, layer.plan.layer_len())?;
    }
    Ok(())
}

/// Append measured layers to the packet layer table.
fn collect_layers(measured: &[MeasuredLayer], layers: &mut Vec<Layer>) {
    layers.reserve(measured.len());
    for measured_layer in measured {
        layers.push(Layer {
            protocol: measured_layer.protocol,
            offset: measured_layer.offset,
            len: measured_layer.plan.layer_len(),
        });
    }
}

#[derive(Debug, Clone, Copy)]
struct MeasuredLayer {
    protocol: &'static dyn Protocol,
    plan: CraftPlan,
    context: CraftContext,
    offset: usize,
}

/// Extension helpers for craft layers.
///
/// These methods are available on any concrete [`CraftLayer`] implementor.
pub trait CraftLayerExt: CraftLayer + Sized {
    /// Start a [`PacketStack`] with this layer as the outermost layer.
    fn into_stack(self) -> PacketStack {
        PacketStack::from_layer(self)
    }

    /// Build this single layer as a packet.
    ///
    /// This is a convenience for `self.stack().build()`.
    fn build(self) -> Result<CraftedPacket, CraftError> {
        self.into_stack().build()
    }
}

impl<T> CraftLayerExt for T where T: CraftLayer + Sized {}

impl<Rhs> Div<Rhs> for PacketStack
where
    Rhs: CraftLayer,
{
    type Output = PacketStack;

    /// Append `rhs` as the next inner layer.
    fn div(mut self, rhs: Rhs) -> Self::Output {
        self.push_layer(rhs);
        self
    }
}

/// Implement `/` composition for a concrete craft-layer builder.
///
/// Protocol modules invoke this next to their builder definition so the
/// ergonomics for built-in and custom builders stay local to the builder type.
/// External crates can use the same macro for their own craft layers:
///
/// ```
/// # use maja::prelude::*;
/// # #[derive(Debug)]
/// # struct ToyBuilder;
/// # #[derive(Debug)]
/// # struct Toy;
/// # impl Protocol for Toy {}
/// # impl CraftLayer for ToyBuilder {
/// #     fn protocol(&self) -> &'static dyn Protocol { &Toy }
/// #     fn measure(
/// #         &self,
/// #         _context: CraftContext,
/// #         child: Option<CraftChildPlan>,
/// #     ) -> Result<CraftPlan, CraftError> {
/// #         Ok(CraftPlan::new(1, 1 + child.map_or(0, |child| child.len())))
/// #     }
/// #     fn write(
/// #         &self,
/// #         _context: CraftContext,
/// #         _plan: CraftPlan,
/// #         _child: Option<CraftChild>,
/// #         bytes: &mut [u8],
/// #     ) -> Result<(), CraftError> {
/// #         bytes[0] = 0xab;
/// #         Ok(())
/// #     }
/// # }
/// maja::impl_craft_layer_div!(ToyBuilder);
/// ```
#[macro_export]
macro_rules! impl_craft_layer_div {
    ($builder:ty) => {
        impl<Rhs> ::core::ops::Div<Rhs> for $builder
        where
            Rhs: $crate::packet::craft::CraftLayer,
        {
            type Output = $crate::packet::craft::PacketStack;

            /// Start a packet stack with this builder and append `rhs`.
            fn div(self, rhs: Rhs) -> Self::Output {
                $crate::packet::craft::PacketStack::from_layer(self) / rhs
            }
        }
    };
}

/// Convert a measured byte length into a `u16` protocol field.
///
/// Protocols such as IPv4, TCP pseudo headers, and UDP carry lengths in
/// 16-bit fields. Builders call this while measuring so oversized packets fail
/// before the final packet buffer is allocated.
pub(crate) fn checked_u16_len(
    protocol: &'static str,
    field: &'static str,
    len: usize,
) -> Result<u16, CraftError> {
    u16::try_from(len).map_err(|_| CraftError::LengthOverflow {
        protocol,
        field,
        len,
        max: u16::MAX as usize,
    })
}

/// Return the sum of two measured byte lengths.
///
/// Builders use this instead of plain `+` when combining header and child
/// lengths, so malformed custom craft layers cannot overflow `usize` before
/// validation runs.
pub(crate) fn checked_add_len(
    protocol: &'static str,
    field: &'static str,
    lhs: usize,
    rhs: usize,
) -> Result<usize, CraftError> {
    lhs.checked_add(rhs).ok_or(CraftError::LengthOverflow {
        protocol,
        field,
        len: lhs,
        max: usize::MAX.saturating_sub(rhs),
    })
}

#[cfg(test)]
mod tests {
    use std::net::Ipv4Addr;

    use super::*;
    use crate::{
        eth, eth_addr, ipv4,
        packet::layer::{
            eth::{Eth, EthType},
            ip::{protocol::IpProtocol, v4::Ipv4},
            raw::Raw,
            tcp::{Tcp, TcpFlags},
            udp::Udp,
        },
        raw, tcp, udp,
    };

    #[test]
    fn crafts_eth_ipv4_udp_raw_stack() {
        let src_mac = eth_addr!("02:00:00:00:00:01");
        let dst_mac = eth_addr!("02:00:00:00:00:02");
        let src_ip = Ipv4Addr::new(192, 0, 2, 1);
        let dst_ip = Ipv4Addr::new(192, 0, 2, 2);

        let packet = (eth!(src: src_mac, dst: dst_mac)
            / ipv4!(src: src_ip, dst: dst_ip)
            / udp!(src: 12_345, dst: 53)
            / raw!(b"hi"))
        .build()
        .expect("craft packet");

        assert_eq!(packet.len(), 14 + 20 + 8 + 2);
        assert_eq!(packet.layers().len(), 4);
        assert_eq!(packet.layers()[0].offset, 0);
        assert_eq!(packet.layers()[0].len, 14);
        assert_eq!(packet.layers()[1].offset, 14);
        assert_eq!(packet.layers()[1].len, 20);
        assert_eq!(packet.layers()[2].offset, 34);
        assert_eq!(packet.layers()[2].len, 8);
        assert_eq!(packet.layers()[3].offset, 42);
        assert_eq!(packet.layers()[3].len, 2);

        let eth = packet.layer_viewer(Eth).expect("eth layer");
        assert_eq!(eth.src(), src_mac);
        assert_eq!(eth.dst(), dst_mac);
        assert_eq!(eth.eth_type(), EthType::Ipv4);

        let ipv4 = packet.layer_viewer(Ipv4).expect("ipv4 layer");
        assert_eq!(ipv4.src(), src_ip);
        assert_eq!(ipv4.dst(), dst_ip);
        assert_eq!(ipv4.protocol(), IpProtocol::Udp);
        assert_eq!(ipv4.total_length(), 20 + 8 + 2);
        assert_ne!(ipv4.checksum().get(), 0);
        assert!(ipv4.validate_checksum());

        let udp = packet.layer_viewer(Udp).expect("udp layer");
        assert_eq!(udp.src_port(), 12_345);
        assert_eq!(udp.dst_port(), 53);
        assert_eq!(udp.length(), 8 + 2);
        assert_ne!(udp.checksum().get(), 0);
        let udp_segment = crate::packet::layer::udp::UdpViewer::new(&packet.as_bytes()[34..]);
        assert!(udp_segment.validate_checksum_ipv4(src_ip, dst_ip));

        let raw = packet.layer_viewer(Raw).expect("raw layer");
        assert_eq!(raw.bytes(), b"hi");
    }

    #[test]
    fn crafts_ipv4_tcp_raw_stack_with_named_fields() {
        let src_ip = Ipv4Addr::new(198, 51, 100, 10);
        let dst_ip = Ipv4Addr::new(198, 51, 100, 20);

        let packet = (ipv4!(src: src_ip, dst: dst_ip, ttl: 128, id: 7)
            / tcp!(
                src: 44_444,
                dst: 80,
                flags: TcpFlags::SYN,
                window: 64_240,
            )
            / raw!(&[]))
        .build()
        .expect("craft packet");

        assert_eq!(packet.len(), 20 + 20);

        let ipv4 = packet.layer_viewer(Ipv4).expect("ipv4 layer");
        assert_eq!(ipv4.ttl(), 128);
        assert_eq!(ipv4.identification(), 7);
        assert_eq!(ipv4.protocol(), IpProtocol::Tcp);
        assert_eq!(ipv4.total_length(), 40);
        assert!(ipv4.validate_checksum());

        let tcp = packet.layer_viewer(Tcp).expect("tcp layer");
        assert_eq!(tcp.src_port(), 44_444);
        assert_eq!(tcp.dst_port(), 80);
        assert_eq!(tcp.flags(), TcpFlags::SYN);
        assert_eq!(tcp.window_size(), 64_240);
        assert_ne!(tcp.checksum().get(), 0);
        assert!(tcp.validate_checksum_ipv4(src_ip, dst_ip));
    }

    #[test]
    fn rejects_raw_with_child_layer() {
        let err = (raw!(b"payload") / udp!(src: 1, dst: 2))
            .build()
            .expect_err("raw cannot have a child");

        assert_eq!(err, CraftError::RawMustBeTerminal);
    }

    #[test]
    fn rejects_implicit_ipv4_payload_gap() {
        let err = (ipv4!(
            src: Ipv4Addr::new(192, 0, 2, 1),
            dst: Ipv4Addr::new(192, 0, 2, 2),
            total_length: 29,
        ) / udp!(src: 1, dst: 2))
        .build()
        .expect_err("payload bytes must be explicit raw layer");

        assert_eq!(
            err,
            CraftError::InvalidField {
                protocol: "ipv4",
                field: "total_length",
                value: 29,
                reason: "must match generated header plus child length; use raw!(...) to add payload bytes",
            }
        );
    }

    #[test]
    fn rejects_implicit_udp_payload_gap() {
        let err = (udp!(src: 1, dst: 2).length(9))
            .build()
            .expect_err("payload bytes must be explicit raw layer");

        assert_eq!(
            err,
            CraftError::InvalidField {
                protocol: "udp",
                field: "length",
                value: 9,
                reason: "must match generated header plus child length; use raw!(...) to add payload bytes",
            }
        );
    }

    #[derive(Debug, Clone, Copy)]
    struct ToyProtocol;

    impl Protocol for ToyProtocol {}

    #[derive(Debug)]
    struct ToyBuilder;

    #[derive(Debug)]
    struct BadPlanBuilder;

    impl CraftLayer for ToyBuilder {
        fn protocol(&self) -> &'static dyn Protocol {
            &ToyProtocol
        }

        fn measure(
            &self,
            _context: CraftContext,
            child: Option<CraftChildPlan>,
        ) -> Result<CraftPlan, CraftError> {
            let child_len = child.map_or(0, |child| child.len());
            Ok(CraftPlan::new(1, 1 + child_len))
        }

        fn write(
            &self,
            _context: CraftContext,
            _plan: CraftPlan,
            _child: Option<CraftChild>,
            bytes: &mut [u8],
        ) -> Result<(), CraftError> {
            bytes[0] = 0xab;
            Ok(())
        }
    }

    impl CraftLayer for BadPlanBuilder {
        fn protocol(&self) -> &'static dyn Protocol {
            &ToyProtocol
        }

        fn measure(
            &self,
            _context: CraftContext,
            _child: Option<CraftChildPlan>,
        ) -> Result<CraftPlan, CraftError> {
            Ok(CraftPlan::new(2, 1))
        }

        fn write(
            &self,
            _context: CraftContext,
            _plan: CraftPlan,
            _child: Option<CraftChild>,
            _bytes: &mut [u8],
        ) -> Result<(), CraftError> {
            Ok(())
        }
    }

    #[test]
    fn custom_layer_can_participate_in_stack() {
        let packet = (eth!(eth_type: EthType::Reserverd(0x88b5)) / ToyBuilder / raw!(b"x"))
            .build()
            .expect("craft custom packet");

        assert_eq!(packet.as_bytes()[14..], [0xab, b'x']);
        assert_eq!(packet.layers().len(), 3);
        assert_eq!(packet.layers()[1].protocol.id(), ToyProtocol.id());
        assert_eq!(packet.layers()[1].offset, 14);
        assert_eq!(packet.layers()[1].len, 1);
        assert_eq!(packet.layers()[2].offset, 15);
        assert_eq!(packet.layer_viewer(Raw).expect("raw layer").bytes(), b"x");
    }

    #[test]
    fn rejects_custom_plan_shorter_than_layer() {
        let err = BadPlanBuilder
            .build()
            .expect_err("total length must cover layer length");

        assert_eq!(
            err,
            CraftError::InvalidLength {
                protocol: "maja::packet::craft::tests::BadPlanBuilder",
                field: "total_len",
                len: 1,
                min: 2,
            }
        );
    }
}
